# Generated by Django 2.2.1 on 2019-05-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='Students',
        ),
    ]
