# Generated by Django 2.2.1 on 2019-06-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20190606_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
