# Generated by Django 2.2.1 on 2019-06-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190606_1843'),
        ('students', '0004_students_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(to='course.Course'),
        ),
    ]
