# Generated by Django 2.2.1 on 2019-05-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration_months', models.IntegerField(max_length=50)),
                ('Course_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
