# Generated by Django 2.2.1 on 2019-06-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_months',
            field=models.IntegerField(),
        ),
    ]
