# Generated by Django 2.2.1 on 2019-06-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('course', '0002_auto_20190606_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='teacher.Teacher'),
        ),
    ]
